name: 'android lint statistics'
description: 'android lint statistics action, aggregate warning counts, generate chart'
author: 'MeilCli'
branding:
  icon: activity
  color: orange
inputs:
  repository:
    description: 'running repository, format: owner/repository'
    required: true
    default: ${{ github.repository }}
  github_token:
    description: 'github token, using to push data branch'
    required: true
    default: ${{ github.token }}
  lint_xml_file_path:
    description: 'android lint reported xml file paths, enable glob pattern'
    required: true
  lint_xml_file_path_follow_symbolic_links:
    description: 'android lint reported xml file paths glob pattern`s follow symbolic links option'
    required: true
    default: 'false'
  data_branch:
    description: 'the saving data branch, this branch is created by this action. if want disable this feature, put empty string'
    default: 'data/lint'
  data_json_file_path:
    description: 'the saving data json file path, this file is created at data branch'
    default: 'data.json'
  data_chart_file_path:
    description: 'the data transition chart png image path, this file is created at your checkouted branch'
    default: 'data.png'
  severity_chart_file_path:
    description: 'the severity chart png image path, this file is created at your checkouted branch'
    required: true
    default: 'severity.png'
  priority_chart_file_path:
    description: 'the priority chart png image path, this file is created at your checkouted branch'
    required: true
    default: 'priority.png'
  report_json_file_path:
    description: 'the report json file path, this file is created at your checkouted branch'
    required: true
    default: 'report.json'
  report_text_file_path:
    description: 'the report text file path, this file is created at your checkouted branch'
    required: true
    default: 'report.txt'
runs:
  using: 'node12'
  main: 'dist/index.js'
